#!/usr/bin/env node
/**
 * build-flows — the flow mockups, built from the real components.
 *
 * `ui_kits/mobile/screens.jsx` is a hand-written mirror: every component is
 * typed out a second time in browser JSX, and every one of them is now a
 * palette behind. This bundles `ui_kits/flows/*.tsx` instead, which imports
 * `src/components` directly. There is no second copy to drift.
 *
 * React stays external and arrives from esm.sh via the host page's import map,
 * so the committed bundle is our source only — small enough to read in a diff.
 * The pages already require a CDN for the Tailwind browser runtime, so this
 * adds no failure mode that wasn't there.
 *
 * Output is committed for the same reason `dist/tokens.plain.css` is: these
 * pages are static, served with `python3 -m http.server`, and a preview that
 * needs a build first is a preview nobody looks at.
 */
import { build } from 'esbuild'

/**
 * Two harnesses, one bundler. `ui_kits/mobile/` was hand-written browser JSX
 * until 2026-08-17; it now imports the same flow definitions this builds for
 * `ui_kits/flows/`, so both entry points pull from one source and neither can
 * fall behind the components.
 */
const ENTRIES = [
  ['ui_kits/flows/main.tsx', 'ui_kits/flows/bundle.js'],
  ['ui_kits/mobile/main.tsx', 'ui_kits/mobile/bundle.js'],
]

for (const [entry, outfile] of ENTRIES) {
  const result = await build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: 'esm',
    target: 'es2022',
    jsx: 'automatic',
    external: ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime'],
    banner: {
      js: `/* Generated by scripts/build-flows.mjs from ${entry}. Do not edit. */`,
    },
    metafile: true,
  })

  const [, out] = Object.entries(result.metafile.outputs)[0]
  console.log(`build-flows: ${(out.bytes / 1024).toFixed(1)} kB -> ${outfile}`)
}
