#!/usr/bin/env node
/**
 * build-flows — the flow mockups, built from the real components.
 *
 * `ui_kits/mobile/screens.jsx` is a hand-written mirror: every component is
 * typed out a second time in browser JSX, and every one of them is now a
 * palette behind. This bundles `ui_kits/flows/*.tsx` instead, which imports
 * `src/components` directly. There is no second copy to drift.
 *
 * React stays external and arrives from esm.sh via the host page's import map,
 * so the committed bundle is our source only — small enough to read in a diff.
 * The pages already require a CDN for the Tailwind browser runtime, so this
 * adds no failure mode that wasn't there.
 *
 * Output is committed for the same reason `dist/tokens.plain.css` is: these
 * pages are static, served with `python3 -m http.server`, and a preview that
 * needs a build first is a preview nobody looks at.
 */
import { build } from 'esbuild'

const result = await build({
  entryPoints: ['ui_kits/flows/main.tsx'],
  outfile: 'ui_kits/flows/bundle.js',
  bundle: true,
  format: 'esm',
  target: 'es2022',
  jsx: 'automatic',
  external: ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime'],
  banner: {
    js: '/* Generated by scripts/build-flows.mjs from ui_kits/flows/*.tsx. Do not edit. */',
  },
  metafile: true,
})

const [, out] = Object.entries(result.metafile.outputs)[0]
console.log(`build-flows: ${(out.bytes / 1024).toFixed(1)} kB -> ui_kits/flows/bundle.js`)
