#!/usr/bin/env node
/**
 * build-tokens — one token source, many consumers.
 *
 * Reads the `@theme` block in src/tokens.css and emits dist/tokens.plain.css
 * as plain `:root` custom properties, so the static harnesses (preview pages,
 * storybook, UI kits) can read the same tokens the shipped package compiles
 * from, without a Tailwind build step.
 *
 * Also emits un-prefixed aliases: `--brand-500: var(--color-brand-500)`. The
 * harnesses were written against short names and there is no reason to make
 * every one of them say `--color-`.
 *
 * Run by `pnpm build`. Editing dist/tokens.plain.css by hand is pointless --
 * it is regenerated.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const SRC = 'src/tokens.css'
const OUT = 'dist/tokens.plain.css'

// The static harnesses run Tailwind from a CDN with no build step. Their
// utilities (bg-brand-500) are generated from `@theme`, and the browser build
// does not process `@theme` out of an imported file -- verified: it fetches
// /src/tokens.css with a 200 and the tokens still never land. Plain `:root`
// custom properties would not help either, because utilities come from the
// theme, not from the variables. So the block is regenerated into them here,
// between markers. Still one source and one command; just injected rather
// than imported.
const HARNESSES = [
  'storybook/index.html',
  'ui_kits/mobile/index.html',
  'ui_kits/app/index.html',
  'ui_kits/desktop-explore.html',
]
const START = '/* build-tokens:start */'
const END = '/* build-tokens:end */'

const css = readFileSync(SRC, 'utf8')
const theme = css.match(/@theme\s*\{([\s\S]*?)\n\}/)
if (theme === null) throw new Error(`No @theme block found in ${SRC}`)

const decls = [...theme[1].matchAll(/^\s*(--[a-z0-9-]+):\s*([^;]+);/gim)]
if (decls.length === 0) throw new Error(`@theme block in ${SRC} declared no tokens`)

const lines = decls.map(([, name, value]) => `  ${name}: ${value.trim()};`)

// Short aliases for the harnesses: --color-fg -> --fg, --text-body -> --body.
// Only for prefixed groups; --radius-*, --font-*, --shadow-* are already short.
const aliases = decls
  .map(([, name]) => name)
  .filter((n) => /^--(color|text)-/.test(n) && !n.includes('--', 2))
  .map((n) => `  ${n.replace(/^--(color|text)-/, '--')}: var(${n});`)

mkdirSync('dist', { recursive: true })
writeFileSync(
  OUT,
  `/* Generated by scripts/build-tokens.mjs from ${SRC}. Do not edit. */\n` +
    `:root {\n${lines.join('\n')}\n\n  /* short aliases */\n${aliases.join('\n')}\n}\n`,
)

console.log(`build-tokens: ${decls.length} tokens + ${aliases.length} aliases -> ${OUT}`)

// Everything after the @theme block — the reduced-motion guard and the
// keyframes — travels with the tokens. The storybook used to hand-copy its own
// @keyframes, which is the same duplication this script exists to remove, and
// without the guard a harness cannot honour prefers-reduced-motion at all.
const trailing = css.slice(css.indexOf(theme[0]) + theme[0].length).trim()

// Regenerate the @theme block inside each static harness.
const themeBlock =
  `${START}\n    @theme {\n` +
  decls.map(([, n, v]) => `      ${n}: ${v.trim()};`).join('\n') +
  `\n    }\n\n` +
  trailing.split('\n').map((l) => (l === '' ? '' : `    ${l}`)).join('\n') +
  `\n    ${END}`

for (const file of HARNESSES) {
  const html = readFileSync(file, 'utf8')
  if (!html.includes(START)) {
    throw new Error(`${file} has no ${START} marker — add one inside its tailwindcss <style> block`)
  }
  const next = html.replace(
    new RegExp(`${START.replace(/[*/]/g, '\\$&')}[\\s\\S]*?${END.replace(/[*/]/g, '\\$&')}`),
    themeBlock,
  )
  writeFileSync(file, next)
  console.log(`build-tokens: theme block -> ${file}`)
}
